site_name: DevOps-Guiden
nav:
    - Planera:
      -  Aktiviteter: Planera/aktiviteter.md
      -  Verktyg: Planera/verktyg.md
    - Utveckla:
      -  Aktiviteter: Utveckla/aktiviteter.md
      -  Verktyg: Utveckla/verktyg.md
    - Bygg:
      -  Aktiviteter: Bygg/aktiviteter.md
      -  Verktyg: Bygg/verktyg.md
    - Testa:
      -  Aktiviteter: Testa/aktiviteter.md
      -  Verktyg: Testa/verktyg.md
    - Leverera:
      -  Aktiviteter: Leverera/aktiviteter.md
      -  Verktyg: Leverera/verktyg.md
    - Driftsätt:
      -  Aktiviteter: Driftsätt/aktiviteter.md
      -  Verktyg: Driftsätt/verktyg.md
    - Förvalta:
      -  Aktiviteter: Förvalta/aktiviteter.md
      -  Verktyg: Förvalta/verktyg.md
    - Bevaka:
      -  Aktiviteter: Bevaka/aktiviteter.md
      -  Verktyg: Bevaka/verktyg.md